---
version: "3"

volumes:
  config:

services:
  audirvana-studio:
    build:
      context: ./build
      args:
        - BINARY_TYPE=studio
    container_name: audirvana-studio
    privileged: true
    network_mode: host
    devices:
      - /dev/snd:/dev/snd
    environment:
      - PUID=${PUID:-}
      - PGID=${PGID:-}
      - AUDIO_GID=${AUDIO_GID:-}
      - ACCEPT_EULA=${ACCEPT_EULA}
    volumes:
      - config:/config
      - /var/run/dbus:/var/run/dbus
      - ${MUSIC_DIRECTORY:-./music}:/music:ro
    restart: unless-stopped
  